// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoRZzzH3eO2XyHu7UT47Ia0ru_4i_XiZo',
    appId: '1:978623706382:web:1006a5d557bf65fe46935f',
    messagingSenderId: '978623706382',
    projectId: 'fir-4428f',
    authDomain: 'fir-4428f.firebaseapp.com',
    storageBucket: 'fir-4428f.appspot.com',
    measurementId: 'G-2B4L4DSWX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAejv-Clz7VYHY7-1d1NjPmlJ4IagAt1zo',
    appId: '1:978623706382:android:9232ee9346afa85d46935f',
    messagingSenderId: '978623706382',
    projectId: 'fir-4428f',
    storageBucket: 'fir-4428f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKL1Haqd1bxM-mKCKdvQbvaCfKbTSPi8M',
    appId: '1:978623706382:ios:6f543e9d51acee8846935f',
    messagingSenderId: '978623706382',
    projectId: 'fir-4428f',
    storageBucket: 'fir-4428f.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKL1Haqd1bxM-mKCKdvQbvaCfKbTSPi8M',
    appId: '1:978623706382:ios:f3e20154e322135746935f',
    messagingSenderId: '978623706382',
    projectId: 'fir-4428f',
    storageBucket: 'fir-4428f.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
